# permissions for end users to edit managedproxyconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedproxyconfiguration-editor-role
rules:
- apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - managedproxyconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - managedproxyconfigurations/status
  verbs:
  - get
