apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    certificateMounting:
      secrets: {}
    certificateSigning:
      type: SelfSigned
  proxyServer:
    image: {{ .Values.proxyServerImage }}
    entrypoint:
      type: LoadBalancerService
      loadBalancerService: {}
  proxyAgent:
    image: {{ .Values.proxyAgentImage }}
    proxyServerHost: